### ISSUE TITLE
Error sending email w/fastmail

### ISSUE THREAD

**Issue by Fizzadar** [Oxygem/Kanmail#138]
**Describe the bug**

Email _does_ send, but then errors!

```URL: http://localhost:57012/api/emails/Fastmail
ErrorName: AttributeError
ErrorMessage: 'str' object has no attribute 'as_string'
Kanmail version: 1.2009020945
Status: 500
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1813, in full_dispatch_request
  File "site-packages/flask/app.py", line 1799, in dispatch_request
  File "kanmail/server/views/email_api.py", line 248, in api_send_account_email
  File "kanmail/server/mail/account.py", line 126, in send_email
  File "kanmail/server/mail/folder.py", line 436, in append_email_message
AttributeError: 'str' object has no attribute 'as_string'```

**Comment by Fizzadar** [comment]
https://github.com/Oxygem/Kanmail/commit/c7224e23c6aa67f63bfd26a31690bed50989d457
