### ISSUE TITLE
Error message in inbox

### ISSUE THREAD

**Issue by nickbe** [Oxygem/Kanmail#160]
Although mails seem to be displayed I see this error:

URL: http://localhost:51098/api/folders
ErrorName: KeyError
ErrorMessage: 'inbox'
Kanmail version: 1.2103140902
Status: 500
Traceback (most recent call last):
  File "lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
  File "lib\site-packages\flask\app.py", line 1799, in dispatch_request
  File "kanmail\server\views\email_api.py", line 31, in api_get_folders
  File "kanmail\server\mail\__init__.py", line 48, in get_all_folders
  File "kanmail\server\util.py", line 86, in execute_threaded
  File "kanmail\server\util.py", line 64, in wrapper
  File "kanmail\server\mail\__init__.py", line 44, in get_folders
  File "kanmail\server\mail\account.py", line 74, in get_folders
KeyError: 'inbox'

**Comment by mzch** [comment]
Here is the same error:

```
URL: http://localhost:61664/api/folders
ErrorName: KeyError
ErrorMessage: 'inbox'
Kanmail version: 1.2101301934
Status: 500
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1813, in full_dispatch_request
  File "site-packages/flask/app.py", line 1799, in dispatch_request
  File "kanmail/server/views/email_api.py", line 31, in api_get_folders
  File "kanmail/server/mail/__init__.py", line 48, in get_all_folders
  File "kanmail/server/util.py", line 86, in execute_threaded
  File "kanmail/server/util.py", line 64, in wrapper
  File "kanmail/server/mail/__init__.py", line 44, in get_folders
  File "kanmail/server/mail/account.py", line 74, in get_folders
KeyError: 'inbox'
```

**Comment by Fizzadar** [comment]
Hi @nickbe @mzch! To help debug this further I need to know which email provider(s) you are both using?

This looks like during account setup Kanmail was unable to determine the "special" IMAP folders. If you could identify the email provider I can take a look; additionally - if you can get these accounts to work in Thunderbird or a different email client, screenshots of the mailbox settings there would be a huge help!

**Comment by nickbe** [comment]
The mail provider is open-xchange based on a standard dovcot server. 
But I think the problem (at least in part) might be due to localization of the folder names. 
Except for INBOX - which is not also shown.

**Comment by Fizzadar** [comment]
Hi @nickbe apologies for the delay in getting back to you on this; do you know what the mailbox names should be? I'm trying to setup a simiilar test environment so I can replicate/fix this!

**Comment by nickbe** [comment]
Cool - thank you !!
