### ISSUE TITLE
Cannot update Kanmail.  win32con module not found.

### ISSUE THREAD

**Issue by edeast** [Oxygem/Kanmail#175]
**Describe the bug**
When trying to update Kanmail to 1.2107081657 receive the following error. 

**Additional context**
URL: http://127.0.0.1:54404/api/update
ErrorName: ModuleNotFoundError
ErrorMessage: No module named 'win32con'
Kanmail version: 1.2107011421
Status: 500
Traceback (most recent call last):
  File "flask\app.py", line 1813, in full_dispatch_request
  File "flask\app.py", line 1799, in dispatch_request
  File "kanmail\server\app.py", line 105, in inner
  File "kanmail\server\views\update_api.py", line 24, in api_download_overwrite_update
  File "kanmail\update.py", line 61, in update_device
  File "pyupdater\client\updates.py", line 771, in extract_overwrite
  File "pyupdater\client\updates.py", line 913, in _win_overwrite
  File "pyupdater\client\updates.py", line 246, in process
  File "pyupdater\client\updates.py", line 300, in _win_overwrite
  File "pyupdater\client\updates.py", line 110, in win_run
ModuleNotFoundError: No module named 'win32con'

**Comment by Fizzadar** [comment]
Thanks for spotting this @edeast! I'm hoping to have a fix for this out v.shortly, I believe the `pywin32` package is missing as it's not a dependency of pyupdater, which does appear to use it.
