### ISSUE TITLE
ErrorMessage: 'gb2312' codec can't decode byte 0xc1 in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by haol666** [Oxygem/Kanmail#178]
**Describe the bug**
URL: http://127.0.0.1:50253/api/emails/haolin.sd@chinatelecom.cn/inbox?reset=true&batch_size=150
ErrorName: UnicodeDecodeError
ErrorMessage: 'gb2312' codec can't decode byte 0xc1 in position 2: illegal multibyte sequence
Kanmail version: 1.2107081657
Status: 500
Traceback (most recent call last):
  File "flask/app.py", line 1813, in full_dispatch_request
  File "flask/app.py", line 1799, in dispatch_request
  File "kanmail/server/app.py", line 107, in inner
  File "kanmail/server/views/email_api.py", line 50, in api_get_account_folder_emails
  File "kanmail/server/mail/__init__.py", line 75, in get_folder_emails
  File "kanmail/server/util.py", line 33, in wrapper
  File "kanmail/server/mail/folder.py", line 454, in get_emails
  File "kanmail/server/mail/folder.py", line 235, in get_email_headers
  File "kanmail/server/mail/util.py", line 101, in make_email_headers
  File "kanmail/server/mail/util.py", line 49, in make_contact_tuples
  File "kanmail/server/mail/util.py", line 49, in <listcomp>
  File "kanmail/server/mail/util.py", line 40, in make_contact_tuple
  File "kanmail/server/mail/util.py", line 151, in decode_header
UnicodeDecodeError: 'gb2312' codec can't decode byte 0xc1 in position 2: illegal multibyte sequence

**Comment by Fizzadar** [comment]
Took years but this should now be fixed in v2 :)
