### ISSUE TITLE
ERROR Unexpected exception in view: Working outside of application context

### ISSUE THREAD

**Issue by malinco** [Oxygem/Kanmail#215]
**Describe the bug**
2023-02-17T15:44:21 ERROR Unexpected exception in view: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.: Traceback (most recent call last):
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "kanmail\server\app.py", line 108, in inner
  File "kanmail\server\views\email_api.py", line 48, in decorated
  File "kanmail\server\views\email_api.py", line 115, in api_get_account_email_texts
  File "kanmail\server\mail\__init__.py", line 222, in get_folder_email_texts
  File "kanmail\server\mail\__init__.py", line 155, in _get_folder_email_parts
  File "kanmail\server\util.py", line 98, in execute_threaded
  File "kanmail\server\util.py", line 76, in wrapper
  File "kanmail\server\mail\__init__.py", line 152, in get_email_parts
  File "kanmail\server\mail\folder.py", line 141, in get_email_parts
  File "kanmail\server\mail\folder.py", line 193, in get_email_headers
  File "kanmail\server\mail\folder_cache.py", line 321, in batch_get_headers
  File "kanmail\server\mail\folder_cache.py", line 302, in batch_get_header_items
  File "kanmail\server\util.py", line 33, in wrapper
  File "kanmail\server\mail\folder_cache.py", line 194, in get_folder_cache_item
  File "flask_sqlalchemy\model.py", line 31, in __get__
  File "sqlalchemy\orm\scoping.py", line 211, in __call__
  File "sqlalchemy\util\_collections.py", line 639, in __call__
  File "flask_sqlalchemy\session.py", line 102, in _app_ctx_id
  File "werkzeug\local.py", line 513, in _get_current_object
RuntimeError: Working outside of application context.

**Screenshots**

**Additional context**

**Comment by Fizzadar** [comment]
v2 rewrites the entire backend so this should be working
