### ISSUE TITLE
Docker image fails to run

### ISSUE THREAD

**Issue by kinga112** [Oxygem/Kanmail#218]
**Describe the bug**

Traceback (most recent call last):
  File "/opt/kanmail/scripts/run_server.py", line 9, in <module>
    from kanmail.server.app import app, boot
  File "/opt/kanmail/./kanmail/server/app.py", line 57, in <module>
    dsn=get_hidden_value("SENTRY_DSN"),
  File "/opt/kanmail/./kanmail/settings/hidden.py", line 37, in get_hidden_value
    data = get_hidden_data()
  File "/opt/kanmail/./kanmail/settings/hidden.py", line 30, in get_hidden_data
    return pickle.loads(b64decode(hidden_data))
  EOFError: Ran out of input

hidden.json is empty so pickle fails.

**Screenshots**

**Additional context**

After a successful docker build, the image fails run.
Using MacOS and python 3.9.18

I tried with honcho as well, but I got other package errors.

**Comment by Fizzadar** [comment]
Docker is no longer supported in v2.
