### ISSUE TITLE
Debian linux compatibility

### ISSUE THREAD

**Issue by gerroon** [Oxygem/Kanmail#90]
Debian Testing X64 Kanmail-nix64-1.2004231151.tar.gz

```
./Kanmail 
/tmp/_MEIehH2bq/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
2020-04-26T17:36:43 WARNING Waiting for main window: HTTPConnectionPool(host='localhost', port=4420): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb024234400>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-04-26T17:36:43 WARNING Waiting for main window: HTTPConnectionPool(host='localhost', port=4420): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb024234b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-04-26T17:36:43 WARNING Waiting for main window: HTTPConnectionPool(host='localhost', port=4420): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb01f71d828>: Failed to establish a new connection: [Errno 111] Connection refused',))
 * Serving Flask app "kanmail" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO]  * Running on http://127.0.0.1:4420/ (Press CTRL+C to quit)
[INFO] 127.0.0.1 - - [26/Apr/2020 17:36:43] "GET /api/ping HTTP/1.1" 200 -

(Kanmail:3804313): dbind-WARNING **: 17:36:43.803: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-sNFAoBubiE: Connection refused

** (Kanmail:3804313): WARNING **: 17:36:43.809: Failed to load shared library 'libwebkit2gtk-4.0.so.37' referenced by the typelib: /tmp/_MEIehH2bq/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37)

** (Kanmail:3804313): WARNING **: 17:36:43.809: Failed to load shared library 'libjavascriptcoregtk-4.0.so.18' referenced by the typelib: /tmp/_MEIehH2bq/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18)
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 102, in main
  File "webview/__init__.py", line 79, in start
  File "webview/guilib.py", line 92, in initialize
  File "webview/guilib.py", line 62, in try_import
  File "webview/guilib.py", line 16, in import_gtk
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/nick/venv_kanmail/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "webview/platforms/gtk.py", line 38, in <module>
gi.repository.GLib.Error: g-invoke-error-quark: Could not locate webkit_get_major_version: /tmp/_MEIehH2bq/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18) (1)
[3804313] Failed to execute script main


```

**Comment by Fizzadar** [comment]
@gerroon I believe this is due to the version of `libc` used to compile Kanmail (per https://pyinstaller.readthedocs.io/en/stable/usage.html#making-gnu-linux-apps-forward-compatible). I'm going to look into compiling on an old version for maximum compatibility.

**Comment by Fizzadar** [comment]
This is indeed `libc`! Am looking into either a) build on an old Linux distro or b) statically link the binary.

Failed to get it working using Ubuntu 14 or static so far, will continue to investigate!

**Comment by Fizzadar** [comment]
So far this is where I've got - https://github.com/Oxygem/Kanmail/pull/107. Cannot get the webkit files to be recognised in the bundle and so amy now stuck :(

**Comment by Fizzadar** [comment]
So the latest release, `v1.2005120955`, is _far_ more portable - but still not working on Debian :( - https://github.com/Oxygem/Kanmail/blob/master/docs/linux.md

**Comment by Fizzadar** [comment]
Replaced by https://github.com/Oxygem/Kanmail/issues/140.
