### ISSUE TITLE
Python install fails

### ISSUE THREAD

**Issue by gerroon** [Oxygem/Kanmail#92]
Ok, now I have tried all 3 methods to run Kanmail (binary, Docker and py dev) and all failed in different ways.

Debian testing 

```python3

Python 3.8.2 (default, Apr  1 2020, 15:52:55) 
[GCC 9.3.0] on linux
```

- python3 -mvenv .venv
- source .venv/bin/activate
- pip install -r requirements/development.txt 
- pip install -r requirements/linux.txt
- honcho start

See below for the log

```
 honcho start
/usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
18:03:49 system   | server.1 started (pid=3816888)
18:03:49 system   | client.1 started (pid=3816889)
18:03:49 server.1 | Traceback (most recent call last):
18:03:49 server.1 |   File "scripts/run_server.py", line 9, in <module>
18:03:49 server.1 |     from kanmail.server.app import app, boot
18:03:49 server.1 |   File "./kanmail/server/app.py", line 11, in <module>
18:03:49 server.1 |     from kanmail.settings.constants import (
18:03:49 server.1 |   File "./kanmail/settings/__init__.py", line 7, in <module>
18:03:49 server.1 |     from pydash import memoize
18:03:49 server.1 |   File "/opt/kanmail/.venv/lib/python3.8/site-packages/pydash/__init__.py", line 12, in <module>
18:03:49 server.1 |     from .arrays import (
18:03:49 server.1 |   File "/opt/kanmail/.venv/lib/python3.8/site-packages/pydash/arrays.py", line 13, in <module>
18:03:49 server.1 |     from .helpers import parse_iteratee, iteriteratee, base_get
18:03:49 server.1 |   File "/opt/kanmail/.venv/lib/python3.8/site-packages/pydash/helpers.py", line 12, in <module>
18:03:49 server.1 |     from ._compat import Iterable, PY2, iteritems, getfullargspec, string_types
18:03:49 server.1 |   File "/opt/kanmail/.venv/lib/python3.8/site-packages/pydash/_compat.py", line 87, in <module>
18:03:49 server.1 |     html_escape = partial(cgi.escape, quote=True)
18:03:49 server.1 | AttributeError: module 'cgi' has no attribute 'escape'
18:03:49 client.1 | yarn run v1.12.3
18:03:49 system   | server.1 stopped (rc=1)
18:03:49 system   | sending SIGTERM to client.1 (pid 3816889)
18:03:49 system   | client.1 stopped (rc=-15)

```

**Comment by Fizzadar** [comment]
@gerroon you'll need to use python `3.7` as this is a breaking change in python 3.8 that the version of `pydash` installed isn't compatible with (it's been fixed, I need to bump the requirement).

Alternatively, just bump your pydash version and it should run.

**Comment by gerroon** [comment]
Hi

I removed the existing .venv and created one with 3.7 (installed all teh requirements as well) and still not working.

`python3.7 -mvenv .venv`


```

honcho start
11:01:09 system   | client.1 started (pid=1516035)
11:01:09 system   | server.1 started (pid=1516036)
11:01:10 client.1 | yarn run v1.12.3
11:01:10 server.1 | 2020-05-01T11:01:10 DEBUG [kanmail.log] Debug level set to: 10
11:01:10 server.1 | 2020-05-01T11:01:10 DEBUG [kanmail.settings.__init__] App dir set to: /home/USER/.config/kanmail
11:01:10 server.1 | 2020-05-01T11:01:10 DEBUG [kanmail.server.app] App client root is: /opt/kanmail/kanmail/client
11:01:10 client.1 | $ NODE_ENV=dev webpack-dev-server --port 4421
11:01:10 client.1 | /bin/sh: 1: webpack-dev-server: not found
11:01:10 client.1 | error Command failed with exit code 127.
11:01:10 client.1 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11:01:10 server.1 | /opt/kanmail/.venv/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
11:01:10 server.1 |   RequestsDependencyWarning)
11:01:10 system   | client.1 stopped (rc=1)
11:01:10 system   | sending SIGTERM to server.1 (pid 1516036)
11:01:10 system   | server.1 stopped (rc=-15)


(.venv) USER@PC:/opt/kanmail$ python
Python 3.7.7 (default, Apr  1 2020, 13:48:52) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.


```

**Comment by Fizzadar** [comment]
This is due to missing the node packages - you'll need to run `yarn` to install them; I've just realised this isn't referenced in the README anywhere which I'm going to update now!
